# Generated by Django 4.2.7 on 2023-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default=str, max_length=40),
            preserve_default=False,
        ),
    ]
