# Generated by Django 4.2.7 on 2023-11-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='image',
            new_name='imagem',
        ),
    ]
